In [60]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [61]:
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [62]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head(50)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Warmbad,NaN,2021-02-01 00:23:14,-28.4500,18.7333,69.78,56,0,16.71
1,1,Sao Geraldo Do Araguaia,BR,2021-02-01 00:26:13,-6.4006,-48.5550,75.11,90,88,0.76
2,2,Komyshnya,UA,2021-02-01 00:26:14,50.1859,33.6840,25.74,97,95,3.38
3,3,Roald,NO,2021-02-01 00:22:59,62.5833,6.1333,28.40,93,20,6.91
4,4,Adre,TD,2021-02-01 00:26:14,13.4667,22.2000,65.52,25,0,10.45
5,5,Vaini,TO,2021-02-01 00:22:17,-21.2000,-175.2000,80.60,89,90,10.36
6,6,Port Elizabeth,ZA,2021-02-01 00:24:04,-33.9180,25.5701,68.00,83,40,24.16
7,7,Busselton,AU,2021-02-01 00:22:16,-33.6500,115.3333,70.00,67,0,8.01
8,8,Kodiak,US,2021-02-01 00:26:15,57.7900,-152.4072,33.80,51,1,5.75
9,9,Rikitea,PF,2021-02-01 00:22:21,-23.1203,-134.9692,79.43,61,25,6.96
10,10,Mataura,NZ,2021-02-01 00:26:15,-46.1927,168.8643,74.59,43,48,1.19
11,11,Gornopravdinsk,RU,2021-02-01 00:22:09,60.0500,69.9000,4.95,94,95,3.78
12,12,Acapulco,MX,2021-02-01 00:22:19,16.8634,-99.8901,82.40,69,20,4.61
13,13,Arraial Do Cabo,BR,2021-02-01 00:22:31,-22.9661,-42.0278,77.45,80,100,28.50
14,14,Sur,OM,2021-02-01 00:26:16,22.5667,59.5289,68.63,55,0,4.21
15,15,Tyubuk,RU,2021-02-01 00:26:16,56.0552,60.9405,13.91,95,0,9.33
16,16,Greymouth,NZ,2021-02-01 00:26:16,-42.4667,171.2000,64.35,61,50,8.86
17,17,Lompoc,US,2021-02-01 00:26:16,34.6391,-120.4579,60.80,63,1,3.44
18,18,Constitucion,CL,2021-02-01 00:22:37,-35.3333,-72.4167,58.14,86,8,8.37
19,19,Odweyne,SO,2021-02-01 00:26:17,9.4092,45.0640,65.03,27,0,12.19
20,20,Lagoa,PT,2021-02-01 00:23:02,39.0500,-27.9833,61.50,87,99,20.40
21,21,Yellowknife,CA,2021-02-01 00:26:17,62.4560,-114.3525,-4.00,77,90,3.44
22,22,Atuona,PF,2021-02-01 00:26:17,-9.8000,-139.0333,78.89,74,46,16.96
23,23,Khromtau,KZ,2021-02-01 00:26:18,50.2503,58.4347,10.71,92,71,6.26
24,24,Punta Arenas,CL,2021-02-01 00:26:18,-53.1500,-70.9167,53.60,62,0,31.07
25,25,Joshimath,IN,2021-02-01 00:26:18,30.5667,79.5667,39.16,41,0,6.93
26,26,Avarua,CK,2021-02-01 00:26:18,-21.2078,-159.7750,82.40,69,20,6.91
27,27,Ushuaia,AR,2021-02-01 00:23:52,-54.8000,-68.3000,53.60,66,75,6.91
28,28,Saint-Philippe,RE,2021-02-01 00:26:19,-21.3585,55.7679,78.80,65,0,8.05
29,29,Provideniya,RU,2021-02-01 00:26:19,64.3833,-173.3000,5.00,85,90,29.08
30,30,Saint George,US,2021-02-01 00:21:48,37.1041,-113.5841,55.40,38,1,3.42
31,31,Sabang,ID,2021-02-01 00:26:19,5.8933,95.3214,80.73,80,68,20.20
32,32,Sao Filipe,CV,2021-02-01 00:26:19,14.8961,-24.4956,73.54,66,0,8.12
33,33,Hobart,AU,2021-02-01 00:22:41,-42.8794,147.3294,75.99,56,75,5.75
34,34,New Norfolk,AU,2021-02-01 00:26:20,-42.7826,147.0587,75.99,48,52,1.99
35,35,Tacoronte,ES,2021-02-01 00:21:42,28.4769,-16.4102,66.00,51,0,4.61
36,36,Sao Joao Da Barra,BR,2021-02-01 00:23:23,-21.6403,-41.0511,77.86,82,97,20.18
37,37,Albany,US,2021-02-01 00:26:20,42.6001,-73.9662,17.01,53,100,2.19
38,38,Bluff,NZ,2021-02-01 00:26:20,-46.6000,168.3333,60.84,68,69,8.05
39,39,Nikolskoye,RU,2021-02-01 00:26:21,59.7035,30.7861,26.01,93,75,6.71
40,40,Tiksi,RU,2021-02-01 00:26:21,71.6872,128.8694,-27.27,86,100,6.40
41,41,Port Alfred,ZA,2021-02-01 00:26:21,-33.5906,26.8910,71.01,85,9,8.99
42,42,Bud,US,2021-02-01 00:26:21,39.4470,-86.1758,32.00,98,100,10.80
43,43,Khatanga,RU,2021-02-01 00:26:21,71.9667,102.5000,-39.32,80,21,8.10
44,44,Arman,RU,2021-02-01 00:26:22,59.7000,150.1667,-17.50,76,82,14.07
45,45,Imbituba,BR,2021-02-01 00:26:22,-28.2400,-48.6703,77.00,83,75,4.61
46,46,Bathsheba,BB,2021-02-01 00:26:22,13.2167,-59.5167,78.80,65,40,25.32
47,47,Marrakesh,MA,2021-02-01 00:26:22,31.6315,-8.0083,53.60,71,0,4.61
48,48,Brae,GB,2021-02-01 00:26:22,60.3964,-1.3530,32.00,86,20,10.36
49,49,Olinda,BR,2021-02-01 00:26:23,-8.0089,-34.8553,78.80,73,40,5.75

In [63]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [64]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [68]:
max_temp = city_data_df["Max Temp"]
temps = []
[max(temp, 0) for temp in max_temp]

[69.78,
 75.11,
 25.74,
 28.4,
 65.52,
 80.6,
 68.0,
 70.0,
 33.8,
 79.43,
 74.59,
 4.95,
 82.4,
 77.45,
 68.63,
 13.91,
 64.35,
 60.8,
 58.14,
 65.03,
 61.5,
 0,
 78.89,
 10.71,
 53.6,
 39.16,
 82.4,
 53.6,
 78.8,
 5.0,
 55.4,
 80.73,
 73.54,
 75.99,
 75.99,
 66.0,
 77.86,
 17.01,
 60.84,
 26.01,
 0,
 71.01,
 32.0,
 0,
 0,
 77.0,
 78.8,
 53.6,
 32.0,
 78.8,
 73.4,
 68.0,
 91.4,
 62.01,
 0,
 61.57,
 15.8,
 41.0,
 12.2,
 81.81,
 56.41,
 30.99,
 3.2,
 57.2,
 51.48,
 0,
 0,
 51.73,
 66.2,
 37.0,
 0,
 28.0,
 80.94,
 74.52,
 25.48,
 28.99,
 52.77,
 0,
 37.4,
 62.01,
 21.99,
 28.4,
 79.0,
 0,
 2.55,
 0,
 82.49,
 55.0,
 30.99,
 77.68,
 62.6,
 80.6,
 64.99,
 51.8,
 0.0,
 3.2,
 0,
 64.4,
 64.0,
 72.82,
 79.65,
 78.8,
 75.76,
 0,
 68.5,
 69.04,
 16.68,
 82.4,
 72.7,
 75.2,
 61.66,
 57.42,
 19.4,
 59.0,
 30.2,
 18.68,
 14.0,
 27.0,
 19.4,
 79.99,
 18.3,
 55.15,
 78.8,
 0,
 0,
 8.6,
 75.47,
 76.87,
 0,
 69.76,
 75.0,
 76.15,
 59.0,
 0,
 79.9,
 64.85,
 23.0,
 75.63,
 80.6,
 44.6,
 87.8,
 72.03,
 66.0,
 48.2,
 59.0,
 39.2,
 19.17,
 75.2,
 0,
 72.28,
 82.4,
 0,
 73.06,
 15.8,
 68.72,
 39.56,
 75.2,
 39.99,
 0,
 15.01,
 78.55,
 73.4,
 76.8,
 30.2,
 23.0,
 77.49,
 44.26,
 75.58,
 0,
 31.46,
 64.0,
 50.0,
 68.5,
 66.45,
 0,
 65.3,
 57.99,
 0,
 45.0,
 68.0,
 12.31,
 55.99,
 64.76,
 66.99,
 74.19,
 80.6,
 80.6,
 5.0,
 67.26,
 78.8,
 75.74,
 23.0,
 50.9,
 69.37,
 0,
 78.55,
 33.8,
 64.4,
 77.11,
 0,
 69.44,
 50.0,
 32.83,
 69.01,
 0,
 75.2,
 77.02,
 37.4,
 76.8,
 71.01,
 56.82,
 32.0,
 80.1,
 6.8,
 75.63,
 86.0,
 50.27,
 64.35,
 43.38,
 24.8,
 73.47,
 0,
 63.0,
 0,
 68.58,
 39.99,
 71.6,
 16.34,
 80.6,
 52.0,
 84.2,
 78.49,
 7.9,
 15.8,
 75.2,
 69.51,
 46.4,
 0,
 59.0,
 76.41,
 14.63,
 0,
 62.71,
 51.8,
 64.36,
 17.22,
 21.2,
 0,
 75.2,
 32.0,
 64.63,
 84.0,
 80.46,
 19.99,
 76.28,
 64.4,
 0,
 76.5,
 65.73,
 66.83,
 73.4,
 37.99,
 32.32,
 82.99,
 45.0,
 0,
 71.67,
 78.89,
 73.63,
 0,
 82.4,
 66.2,
 81.25,
 6.8,
 90.27,
 66.29,
 78.22,
 48.2,
 67.82,
 8.28,
 66.96,
 23.0,
 39.2,
 0,
 77.5,
 55.4,
 74.62,
 75.2,
 78.8,
 39.0,
 78.67,
 73.76,
 50.0,
 77.94,
 66.87,
 12.99,
 77.52,
 78.8,
 13.59,
 23.0,
 16.0,
 46.0,
 82.17,
 5.0,
 55.0,
 22.84,
 81.5,
 80.6,
 80.91,
 62.01,
 18.32,
 80.01,
 11.08,
 9.21,
 79.93,
 66.2,
 33.15,
 47.73,
 46.99,
 78.48,
 59.07,
 89.01,
 48.67,
 71.53,
 59.0,
 25.3,
 39.2,
 36.0,
 41.0,
 19.4,
 72.55,
 59.0,
 0,
 62.8,
 41.49,
 84.2,
 72.18,
 23.9,
 68.9,
 77.0,
 68.0,
 78.26,
 73.49,
 63.12,
 12.2,
 33.01,
 80.89,
 80.26,
 0,
 84.51,
 78.82,
 86.0,
 0,
 82.4,
 77.0,
 57.2,
 48.99,
 22.26,
 46.33,
 23.0,
 54.45,
 78.01,
 33.1,
 18.0,
 78.8,
 15.31,
 28.4,
 17.19,
 62.31,
 61.29,
 54.0,
 75.56,
 26.6,
 69.01,
 58.5,
 3.72,
 87.39,
 60.8,
 48.87,
 75.54,
 84.22,
 65.21,
 64.0,
 26.6,
 75.2,
 49.03,
 0,
 68.0,
 8.38,
 17.01,
 26.87,
 84.2,
 0,
 0,
 79.0,
 77.0,
 80.6,
 72.86,
 0,
 0,
 66.96,
 80.19,
 22.44,
 0,
 74.03,
 20.23,
 30.0,
 0,
 62.92,
 63.0,
 76.68,
 37.0,
 49.91,
 63.73,
 56.3,
 75.2,
 6.8,
 62.31,
 0,
 19.4,
 0,
 17.98,
 32.0,
 0,
 48.2,
 78.93,
 17.56,
 64.4,
 37.0,
 82.4,
 80.6,
 42.01,
 57.2,
 71.6,
 76.93,
 93.0,
 12.87,
 60.8,
 69.24,
 60.8,
 28.99,
 31.35,
 85.26,
 0,
 53.6,
 59.0,
 80.6,
 0,
 82.89,
 70.09,
 72.27,
 39.99,
 84.0,
 73.4,
 73.29,
 73.45,
 75.2,
 78.8,
 26.01,
 16.54,
 79.39,
 13.68,
 64.0,
 80.11,
 46.27,
 21.2,
 76.28,
 0,
 77.83,
 77.99,
 72.28,
 62.2,
 83.79,
 42.8,
 30.99,
 69.98,
 78.01,
 36.0,
 37.0,
 39.99,
 69.8,
 80.6,
 50.0,
 75.7,
 51.8,
 46.0,
 72.64,
 81.79,
 78.8,
 70.0,
 84.2,
 18.39,
 0,
 50.0,
 76.35,
 65.84,
 10.4,
 33.01,
 37.99,
 2.84,
 86.0,
 62.49,
 45.84,
 15.8,
 71.98,
 28.69,
 68.18,
 82.4,
 78.8,
 82.4,
 81.9,
 58.66,
 78.8,
 19.31,
 23.67,
 0,
 0,
 0,
 71.6,
 25.0,
 71.6,
 17.6,
 69.49,
 71.49,
 77.0,
 77.0,
 72.0,
 66.2,
 66.79,
 58.96,
 15.8,
 79.75,
 0,
 76.84,
 69.8,
 48.99,
 87.8,
 21.2,
 42.01,
 36.86,
 0,
 0,
 67.71,
 75.16,
 79.0,
 66.97,
 64.99,
 59.5,
 75.0,
 5.68,
 58.41,
 30.9,
 87.8,
 67.86,
 57.99,
 76.87,
 77.88,
 12.0,
 73.42,
 48.2,
 81.48,
 73.4,
 21.29,
 44.6,
 67.84,
 40.37,
 10.4,
 41.0,
 39.2,
 5.0,
 18.32,
 71.2,
 62.6,
 80.6,
 69.51,
 80.6,
 79.0,
 44.6,
 72.0,
 79.2,
 60.87,
 48.34,
 57.6]

In [70]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]


# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [75]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]


# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [73]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [76]:
# Heatmap of Cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds= city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [77]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [80]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [93]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Sao Geraldo Do Araguaia,BR,2021-02-01 00:26:13,-6.4006,-48.5550,75.11,90,88,0.76
5,5,Vaini,TO,2021-02-01 00:22:17,-21.2000,-175.2000,80.60,89,90,10.36
9,9,Rikitea,PF,2021-02-01 00:22:21,-23.1203,-134.9692,79.43,61,25,6.96
12,12,Acapulco,MX,2021-02-01 00:22:19,16.8634,-99.8901,82.40,69,20,4.61
13,13,Arraial Do Cabo,BR,2021-02-01 00:22:31,-22.9661,-42.0278,77.45,80,100,28.50
...,...,...,...,...,...,...,...,...,...,...
560,560,Lethem,GY,2021-02-01 00:28:04,3.3803,-59.7968,81.48,66,69,11.56
573,573,Koungou,YT,2021-02-01 00:28:07,-12.7336,45.2042,80.60,83,0,2.30
575,575,Isabela,PH,2021-02-01 00:28:07,6.7085,121.9711,80.60,78,90,4.61
576,576,Cap Malheureux,MU,2021-02-01 00:28:07,-19.9842,57.6142,79.00,77,27,4.00
579,579,Palu,ID,2021-02-01 00:24:07,-0.8917,119.8707,79.20,74,90,1.45

In [94]:
preferred_cities_df.count()

City_ID       153
City          153
Country       153
Date          153
Lat           153
Lng           153
Max Temp      153
Humidity      153
Cloudiness    153
Wind Speed    153
dtype: int64

In [96]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                       City Country  Max Temp      Lat       Lng Hotel Name
1   Sao Geraldo Do Araguaia      BR     75.11  -6.4006  -48.5550
5                     Vaini      TO     80.60 -21.2000 -175.2000
9                   Rikitea      PF     79.43 -23.1203 -134.9692
12                 Acapulco      MX     82.40  16.8634  -99.8901
13          Arraial Do Cabo      BR     77.45 -22.9661  -42.0278
22                   Atuona      PF     78.89  -9.8000 -139.0333
26                   Avarua      CK     82.40 -21.2078 -159.7750
28           Saint-Philippe      RE     78.80 -21.3585   55.7679
31                   Sabang      ID     80.73   5.8933   95.3214
33                   Hobart      AU     75.99 -42.8794  147.3294

In [97]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [98]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'ATtYBwL9f1TOLfhYvMrKmLc1nlu9UKUrjhB0c3gnC9or6djUDFIsoB4k5is2ztrtk7KA6TQmiZkeIj31GrKdZl0BErLQON3e41ZnHZQo3a8VC48LfHIQQT7D7TypCZTHzuKUYMw9aPj8r-VCHe2rFmeTpMQGCXCgEsvtcelCYA291uk1dixyTUUFa0KlGWTZPE708XOWjVzim4n-0jBZ1zYZ0OLiU1_nJ-KYN99Ca4Nzsb0fP1Fd18MZ9r_spr9gwvQ5lAfU-m58ajGgIokLC1TqhlTnlhE27s25P2xRIgImLeiyC3NCgVNGrS5dCWCR8N1JIUogKfIS_E06ve0I3vcu5vnl82AgiyuAIocC4c16t4d0MQn_DRmY7EA9au_1WVaIjd60hRsnciX62AzgNQMHqnoXclTuci8GWsBaS7OtWe7bUOA0HwgmD2iL',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594393802915,
      'lng': 2.354352980291503},
     'southwest': {'lat': 48.8567414197085, 'lng': 2.351655019708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'ATtYBwIDnQi7-dy3O-uU-fHtjgPO1UEXIYPKs0Adt9hqitY4Gv8pEPbgzeau5o2fmexcR97zGEPV3VYddh1lMAN7BH7RVy3CLjDArhpcHk8WcCfh-wmVq6oOiqz9hk8bosCoIH5kw1yyZOAEEABE16oBF2nDCQxBF6s25H0mi4Dysw1cOqti',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 278,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Britannique',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 546,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Louvre</a>'],
     'photo_reference': 'ATtYBwLkIDTL-Mq527pE01gNFvoowCVjR3tzGKflHQBQNBQXRCyTVm4iJ1JAitLlRep9yV9z1spT39UJEP26xChisLTA-qnjeasJMIyfFGhGwlgZAQqnXe3A0KLmdRaoMU4mTr9PX8-DgziphBfdcxvMXYiV4pWhcdFmNi558KCY3zEHymDD',
     'width': 1024}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 422,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.86176813029151,
      'lng': 2.348040180291502},
     'southwest': {'lat': 48.85907016970851, 'lng': 2.345342219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Citadines Les Halles Paris (Apart Hotel Paris)',
   'permanently_closed': True,
   'photos': [{'height': 496,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'ATtYBwIF6O7xbhP0V6nUwGcqBP_iO_WtWU7cpl8A9fmh9uH6U1653WWl757MM-1jipWAG32N1P0bVS-iIlQd5UlA6ZIgAZ_uIY46-YnigFzv7nieTmWIrZTwKHt37IRdWmPArISjLCry-mGz8q7EhxWvYoF4s8SfWdRZUn4kSkI-qlAjjnXM',
     'width': 745}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 817,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607769, 'lng': 2.3463217},
    'viewport': {'northeast': {'lat': 48.8620135802915,
      'lng': 2.347597080291502},
     'southwest': {'lat': 48.8593156197085, 'lng': 2.344899119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel</a>'],
     'photo_reference': 'ATtYBwLSq-3k1nF69VrEboXd_XKlu2g5e-DUFt5GSQGSGBFpWqg_XqUcZpr1mxV3QlRmyCuQf1ScMtBxkjXDrm-LZDhfBIzM1wlOv2tkxOcZDpI0B7kWcJ_HoPyQBHGd11J90UGXTbJ4xAofz5OaLT4QPfdymJrbr5HQFnashADF-aBfVObw',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8G Paris, France',
    'global_code': '8FW4V86W+8G'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2090,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Best Western Premier Ducs de Bourgogne</a>'],
     'photo_reference': 'ATtYBwJzkrCYYDRCw2GS-3G_BkkpLJ0R7e9HFjyfksvmuRj1-XSKb6jt3WOiDt_dZdpiFYo6vbv4dNoiI1-XZtVVwdJv3PTGCKp4hFWGD_spWyiIEragbSHT_Iudi7VCikENmr-BopRPQnVNNWYXgjaJptmEFuvLO0h4lzEFu5TSXDCVlwL8',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 275,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Citadines Saint-Germain-des-Prés Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107856881779358840274">David O&#39;Meara</a>'],
     'photo_reference': 'ATtYBwIJ3viqbkx9QKnqPVUGWO71tfmJ_d9TSInzu5mSwUbmxtaqAf_BclPbXoQxnSVQ6GXQcOhA9S7UhDVA-4nmJWhqKKz9C0bFU8-t4wA31RqEYXu18OExGyJj-2k_CEU7v75V1omWLnEchLNTZ3ALJAeNRvCwJGfOSbPM3UiNkCJKX-_7',
     'width': 4032}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 654,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064},
    'viewport': {'northeast': {'lat': 48.8677623302915,
      'lng': 2.361952180291502},
     'southwest': {'lat': 48.8650643697085, 'lng': 2.359254219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'ATtYBwJ_UlTJGYDUz6jzdjSuCqVZxcM1d_Zab2CeyY3K5f6iNTiOZ0rTRU7wFVfAUa-9LW2-WQ0_rzsipaLLZpU1ZBapyT3MqDEZXH2mUqP2vaRi2B8hBpI2m9gBD-5gKP6vzmJBjz7K36bda2trekXfh-HOS_JpVQ4IwhK-_XzgRHcx8Vy9',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 376,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'ATtYBwJGd31QZQoqaxMTr3tDlV8l0Svdj38VrYG1BG5xJnyjPUutacHtwt6JRa4Xy0y5edDS6HHTn6UGWA44-dXDcWHEyrtMTnVveBcxaMqL20a01hNxI3net0uUgiN9gzX2phx93IaHFnvwiORdDKD8NVp8dX0gtBfD3E6VxSiPycNuVjib',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 504,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.84922153029149,
      'lng': 2.372321980291502},
     'southwest': {'lat': 48.84652356970849, 'lng': 2.369624019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102166088584622554231">cherry pyj</a>'],
     'photo_reference': 'ATtYBwLQoyxHi5ahzH-wD12HN834f0G1lwLNLvETmqm4Vmrt4mqoOtcFqsxHwic1fckYdmco2w6eFaV-5Lr2l86UG32ddijT7lmq_JGaZ_4b3haAcwE4sZPih_fqP-7T-IZxnfB-Yhl_SsquPVBTKgNUQJq--fG_J_SFWikZDEVrA_h74CuW',
     'width': 4032}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 750,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488750302915,
      'lng': 2.373125480291502},
     'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112792427704207973717">salva ubeda</a>'],
     'photo_reference': 'ATtYBwLLioyHBpGbzXCT5Sxfk4I3LEaAjRwPTW4TD6y_0wQmTqbPSJ7DSZEZianpq1sUOn4s6nOsGJ5c1aS7L__tKzDoXXwY_NfaCAo1WvSgtdaeqQRi5XjgnxwSRgjhWZRssku4Q1evZcYDF26WRmOtcyqaxRFD9NlpieMPQKsjnrctzZym',
     'width': 6000}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 380,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Prélude Opéra',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105311226083684825186">Shin-ichi Fukuyama</a>'],
     'photo_reference': 'ATtYBwJtToYcZdInq8mYFgo-nGV1v16XCV9jJomtndww7UprSCoosrnv2IcQ035AsT1-pINl9ZJXvfvoTSyEifcy6Gs18lGzq6HjVePyZvc1m9ubjCkl_oqviEnEhbx7s-aAZNVViEAyCZRsxS85R6-osT3O2C817gg8tevmHAdUsqaaY6sf',
     'width': 4032}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 316,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423491, 'lng': 2.3632246},
    'viewport': {'northeast': {'lat': 48.84365308029151,
      'lng': 2.364707180291502},
     'southwest': {'lat': 48.84095511970851, 'lng': 2.362009219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'ATtYBwLdCVcUImTA8EQycXO6qG-NnNpfD-bdBVgTrRpeb4wSm7yX2xzupcTKhDzOHd8J3xK-wEeB5uRMV34jj4jCdPyQMKDcw4md6U3UaTp0wvMH1GMY0hOlwzPR52CafEfQnuycQwArdS_S5mq2_Pf_sfI_3w5t4MrE86L9jj-R08YX94gA',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 433,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655772302915,
      'lng': 2.332153880291502},
     'southwest': {'lat': 48.8628792697085, 'lng': 2.329455919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1365,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'ATtYBwJSlbDgf5aYVG4ioYZY-vr2nYZ8ZOGW2S4L076ZCEm1CGOZcjkUHM_LFrHgU37OJnAd8JvqL42RqOOyuJCssNeWu5Th7vSvht2Ysv7xuZgbz_aIa4LV2GiUPfUZewIwZGZsAdM2Zsj5TlwofWmiiUQIk_i-Z_X23OGUh9IZk7bVRezU',
     'width': 2048}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1073,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724296802915,
      'lng': 2.340311380291503},
     'southwest': {'lat': 48.8697317197085, 'lng': 2.337613419708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],
     'photo_reference': 'ATtYBwKw27iqGT6JmywREBCH1DPFllbXfvNW34v1SkPDlvTNqAnYLn-ZcEjmM6LfwJ6uJp-umn83gy9OIGvfsuFQQCrQ__5Vfzr_-EtcJ2RG-BpI7hGL9RkyshUcWkEfjHA5d8emETEcHJQLUTXDZeGeySV6rgSHsvDkTmxPzNPpyjygkzuA',
     'width': 1600}],
   'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'plus_code': {'compound_code': 'V8CQ+CH Paris, France',
    'global_code': '8FW4V8CQ+CH'},
   'rating': 3.7,
   'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 134,
   'vicinity': "4 Rue d'Amboise, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8654924, 'lng': 2.3271121},
    'viewport': {'northeast': {'lat': 48.86678673029151,
      'lng': 2.328593580291502},
     'southwest': {'lat': 48.86408876970851, 'lng': 2.325895619708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'The Westin Paris - Vendôme',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 810,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105819208076758962074">The Westin Paris - Vendôme</a>'],
     'photo_reference': 'ATtYBwLg215h93W24ZfinXCs7BDzN4UNppJDJs1LgD0i2AaGCt6d-codv8-I7-csMJ9r79oppJ67iXcGUbKq8dWzobF5WwlPDCbv-5_adNjcOtyXZU8b8Bjd8ZgdS6LobQvwRCuFSmPpCnhSPeHZGmb-XoxSlNkzRNpr_HOObeT3eX4xXltv',
     'width': 1440}],
   'place_id': 'ChIJt4LY5C1u5kcRvVeuJebPxHc',
   'plus_code': {'compound_code': 'V88G+5R Paris, France',
    'global_code': '8FW4V88G+5R'},
   'rating': 4.3,
   'reference': 'ChIJt4LY5C1u5kcRvVeuJebPxHc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2042,
   'vicinity': '3 Rue de Castiglione, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86038899999999, 'lng': 2.323112},
    'viewport': {'northeast': {'lat': 48.8617804302915,
      'lng': 2.324489280291502},
     'southwest': {'lat': 48.8590824697085, 'lng': 2.321791319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "Hôtel d'Orsay",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 768,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115556676131195822021">Hôtel 4 étoile d&#39;Orsay Paris 7ème</a>'],
     'photo_reference': 'ATtYBwJJ0SpllrjZbKHgAqscaLFEZG3b9k2kPzSAqK2cw40OarKO2LR9ECsIAUC0TQ4sHyPR3fC3WIBGqpIiupZaNeblVrXTSVvt4PQdUr2k6lLR3TE0Lj0D3dQr0krMiqgWXkw_VQ1WBquIbIGvDyTLFkydjKbe8ulZ0bmNqw8UA6a3VN93',
     'width': 1152}],
   'place_id': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'plus_code': {'compound_code': 'V86F+56 Paris, France',
    'global_code': '8FW4V86F+56'},
   'rating': 4.6,
   'reference': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 207,
   'vicinity': '93 Rue de Lille, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8661363, 'lng': 2.3260648},
    'viewport': {'northeast': {'lat': 48.8674534302915,
      'lng': 2.327513280291502},
     'southwest': {'lat': 48.8647554697085, 'lng': 2.324815319708498}}},

In [99]:
len(hotels["results"])

20

In [108]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [110]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Sao Geraldo Do Araguaia,BR,75.11,-6.4006,-48.5550,SOLAR DO BARROSO
5,Vaini,TO,80.60,-21.2000,-175.2000,Keleti Beach Resort
9,Rikitea,PF,79.43,-23.1203,-134.9692,Pension Maro'i
12,Acapulco,MX,82.40,16.8634,-99.8901,HS Hotsson Smart Acapulco
13,Arraial Do Cabo,BR,77.45,-22.9661,-42.0278,Pousada Porto Praia
22,Atuona,PF,78.89,-9.8000,-139.0333,Villa Enata
26,Avarua,CK,82.40,-21.2078,-159.7750,Paradise Inn
28,Saint-Philippe,RE,78.80,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
31,Sabang,ID,80.73,5.8933,95.3214,Hotel Citra
33,Hobart,AU,75.99,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania

In [112]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [114]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [115]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))